// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByBSKb9Ny9g5cehWTc_2u115uN1srOd8c',
    appId: '1:102159320619:web:cf201ffb2ff7efe7348c6e',
    messagingSenderId: '102159320619',
    projectId: 'device-streaming-10a3a7b7',
    authDomain: 'device-streaming-10a3a7b7.firebaseapp.com',
    storageBucket: 'device-streaming-10a3a7b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtQG_XRuuQALKnl-kzfA8-kCn49NXTIh0',
    appId: '1:102159320619:ios:c0216e3303825eda348c6e',
    messagingSenderId: '102159320619',
    projectId: 'device-streaming-10a3a7b7',
    storageBucket: 'device-streaming-10a3a7b7.firebasestorage.app',
    iosBundleId: 'com.example.contactApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtQG_XRuuQALKnl-kzfA8-kCn49NXTIh0',
    appId: '1:102159320619:ios:c0216e3303825eda348c6e',
    messagingSenderId: '102159320619',
    projectId: 'device-streaming-10a3a7b7',
    storageBucket: 'device-streaming-10a3a7b7.firebasestorage.app',
    iosBundleId: 'com.example.contactApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByBSKb9Ny9g5cehWTc_2u115uN1srOd8c',
    appId: '1:102159320619:web:7e0dcdf754160aa4348c6e',
    messagingSenderId: '102159320619',
    projectId: 'device-streaming-10a3a7b7',
    authDomain: 'device-streaming-10a3a7b7.firebaseapp.com',
    storageBucket: 'device-streaming-10a3a7b7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrtG-mvaEPllR1RYhYGXyXpO6cc0Wdgg0',
    appId: '1:102159320619:android:08d779df42a57ea0348c6e',
    messagingSenderId: '102159320619',
    projectId: 'device-streaming-10a3a7b7',
    storageBucket: 'device-streaming-10a3a7b7.firebasestorage.app',
  );

}